#!/bin/bash
#### ---- stopping rrwatchdoge after startup ---- ####
sleep 30
service rrwatchdoge stop

#### ---- create new logging folder from tmpfs and link logs to /dev/null ---- ####
mountpoint -q /mnt/data/rockrobo/rrlog || mount -t tmpfs -o size=5m ext4 /mnt/data/rockrobo/rrlog
ln -s /dev/null /mnt/data/rockrobo/rrlog/watchdog.log
ln -s /dev/null /mnt/data/rockrobo/rrlog/rrlog.log
ln -s /dev/null /mnt/data/rockrobo/rrlog/miio.log

#### ---- remove existing .log and .old files ---- ####
rm /dev/shm/*.old

#### ---- check if reboot/remount has occured to reset the symlinks for log files ---- ####
        rm /dev/shm/*.log

#### ---- finally start rrwatchdoge ---- ####
service rrwatchdoge start
