#!/bin/bash
#### ---- stopping rrwatchdoge after startup ---- ####
sleep 30
service rrwatchdoge stop

#### ---- create new logging folder from tmpfs and link logs to /dev/null ---- ####
mount -t tmpfs -o size=5m ext4 /mnt/data/rockrobo/rrlog
ln -s /dev/null /mnt/data/rockrobo/rrlog/watchdog.log
ln -s /dev/null /mnt/data/rockrobo/rrlog/rrlog.log
ln -s /dev/null /mnt/data/rockrobo/rrlog/miio.log

#### ---- remove existing .log and .old files ---- ####
rm /dev/shm/*.log
rm /dev/shm/*.old

#### ---- check if reboot/remount has occured to reset the symlinks for log files ---- ####
if [ ! -f "/dev/shm/check" ]; then
        ln -s /dev/null /dev/shm/APP_PROXY_normal.log
        ln -s /dev/null /dev/shm/NAV_TRAP_normal.log
        ln -s /dev/null /dev/shm/NAV_binId5.log
        ln -s /dev/null /dev/shm/NAV_binId6.log
        ln -s /dev/null /dev/shm/PLAYER_SERVER_normal.log
        ln -s /dev/null /dev/shm/PLAYER_fprintf.log
        ln -s /dev/null /dev/shm/PLAYER_normal.log
        ln -s /dev/null /dev/shm/PLAYER_SERVER_fprintf.log
        ln -s /dev/null /dev/shm/SLAM_fprintf.log
        ln -s /dev/null /dev/shm/SLAM_normal.log
        echo . > /dev/shm/check
fi

#### ---- finally start rrwatchdoge ---- ####
service rrwatchdoge start
