#!/bin/bash

#### ---- unmount logging folder ---- ####
umount /mnt/data/rockrobo/rrlog

#### ---- following lines check Filesystem ---- ####
umount /mnt/updbuf
umount /mnt/data
umount /mnt/reserve
umount /mnt/default
fsck -y /dev/mmcblk0p10
fsck -y /dev/mmcblk0p1
fsck -y /dev/mmcblk0p11
fsck -y /dev/mmcblk0p6
mount /dev/mmcblk0p10 /mnt/updbuf
mount /dev/mmcblk0p1 /mnt/data
mount /dev/mmcblk0p11 /mnt/reserve
mount -o ro /dev/mmcblk0p6 /mnt/default

#### ---- create new logging folder from tmpfs and link logs to /dev/null ---- ####
mount -t tmpfs -o size=5m ext4 /mnt/data/rockrobo/rrlog
ln -s /dev/null /mnt/data/rockrobo/rrlog/watchdog.log
ln -s /dev/null /mnt/data/rockrobo/rrlog/rrlog.log
ln -s /dev/null /mnt/data/rockrobo/rrlog/miio.log

#### ---- remove existing .log and .old files ---- ####
rm /dev/shm/*.log
rm /dev/shm/*.old

#### ---- check if reboot/remount has occured to reset the symlinks for log files ---- ####
if [ ! -f "/dev/shm/check" ]; then
        ln -s /dev/null /dev/shm/APP_PROXY_normal.log
        ln -s /dev/null /dev/shm/NAV_TRAP_normal.log
        ln -s /dev/null /dev/shm/NAV_binId5.log
        ln -s /dev/null /dev/shm/NAV_binId6.log
        ln -s /dev/null /dev/shm/PLAYER_SERVER_normal.log
        ln -s /dev/null /dev/shm/PLAYER_fprintf.log
        ln -s /dev/null /dev/shm/PLAYER_normal.log
        ln -s /dev/null /dev/shm/PLAYER_SERVER_fprintf.log
        ln -s /dev/null /dev/shm/SLAM_fprintf.log
        ln -s /dev/null /dev/shm/SLAM_normal.log
        echo . > /dev/shm/check
fi
